const ayarlar = {
  TOKEN: "OTA2MTY1NzMzOTQyMjYzODY4.YYUqmg.d_kuJpVEHrx7bs4fLVyN9vLxEaY", // ASSAGIYI OKU
  sahip: "",
  prefix: "!"
};

module.exports = ayarlar;

//BOT TOKENINIZI EGER BOT GLITCHDE KALACAK
//ISE .ENV DOSYASINA
//EGER VDS YE KURACAK ISENIZ YUKARIYA 1. SATIRA YAZIN
